config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :contents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
	def index
		@contents = Content.all
	end

	def new
		@content = Content.new
	end

	def create
		@content = Content.new(blog_param)
		@content.save
		redirect_to contents_path
	end

	def show
		@content = Content.find(params[:id])
	end

	def destroy
		Content.find(params[:id]).destroy
		redirect_to contents_path
	end

	def blog_param
		params.require(:content).permit(:title, :description, :name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/index.html.erb
<div align="right"><%= link_to 'New' ,  new_content_path%></div>
	<table border="0" align="center" width="70%">
	<tr>
		<td align="center"><h1>Blog</h1></td>
	</tr>
	<% @contents.each do |content| %>
	<tr align="center">
		<td><%= content.title %><hr></td>
	</tr>
	<tr>
		<td style="text-indent: 50px"><%= (content.description).truncate(200) %><%= link_to 'Read' , content_path(content.id)%><hr></td>
	</tr>
	<tr align="right">
		<td>Author:<%= content.name %></td>
	</tr>
	<tr>
		<td align="center">******************************************</td>
	</tr>
	<tr>
		<td><br><br></td>
	</tr>
	<% end %>
</table>

app/views/contents/new.html.erb
<%= form_with(model: @content, local: true) do |form| %>
<table border="0" align="center">
	<tr>
		<td colspan="2"><h1> Create Blog</h1></td>
	</tr>
	<tr>
		<td><%= form.label :title %></td>
		<td><%= form.text_field :title, id: :blog_title %></td>
	</tr>
	<tr>
		<td><%= form.label :description %></td>
		<td><%= form.text_area :description, id: :blog_description %></td>
	</tr>
	<tr>
		<td><%= form.label :name %></td>
		<td><%= form.text_field :name, id: :author_name %></td>
	</tr>
	<tr>
		<td colspan="2"><%= form.submit :id => "create_new" %></td>
	</tr>
</table>
<% end %>

app/views/contents/show.html.erb
<%= link_to 'Back' ,  contents_path%>
	<table border="0" align="center" width="70%">
	<tr>
		<td align="center"><h1>Blog</h1></td>
	</tr>
	<tr align="center">
		<td><%= @content.title %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to 'Delete' ,  content_path(@content.id), :method => 'delete'%><hr></td>
	</tr>
	<tr>
		<td style="text-indent: 50px"><%= @content.description %><hr></td>
	</tr>
	<tr align="right">
		<td>Author:<%= @content.name %></td>
	</tr>
	<tr>
		<td align="center">******************************************</td>
	</tr>
	<tr>
		<td><br></td>
	</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>